<template>
  <v-stepper non-linear v-model="e1">
    <v-stepper-header>
      <v-stepper-step :complete="e1 > 1" step="1" editable>Who Are You?</v-stepper-step>
      <v-divider></v-divider>

      <v-stepper-step :complete="e1 > 2" step="2" editable>E-Mail</v-stepper-step>
      <v-divider></v-divider>

      <v-stepper-step :complete="e1 > 3" step="3" editable>Password</v-stepper-step>
      <v-divider></v-divider>

      <v-stepper-step :complete="e1 > 4" step="4">Finish</v-stepper-step>
    </v-stepper-header>

    <v-stepper-items>
      <v-stepper-content step="1" wid>
        <v-layout column>
          <v-btn color="accent">Log In with Strava</v-btn>
          <v-text-field label="Name" v-model="name" single-line></v-text-field>
          <v-text-field label="Last Name" v-model="lastname" single-line></v-text-field>
          <v-btn color="primary" @click="e1 = 2">Continue</v-btn>
          <v-btn flat>Cancel</v-btn>
        </v-layout>
      </v-stepper-content>

      <v-stepper-content step="2">
        <v-layout column>
          <v-text-field :rules="[rules.required, rules.emailValid]"
                        name="input-10-2"
                        label="Email"
                        value=""
                        v-model="email"></v-text-field>
          <v-btn color="primary" @click="e1 = 3">Continue</v-btn>
          <v-btn flat>Cancel</v-btn>
        </v-layout>
      </v-stepper-content>

      <v-stepper-content step="3">
        <v-layout column wrap>
          <v-flex xs12 sm6>
            <v-text-field
              :append-icon="show ? 'visibility_off' : 'visibility'"
              :rules="[rules.required, rules.min]"
              :type="show ? 'text' : 'password'"
              name="input-10-2"
              label="Password"
              hint="At least 8 characters"
              value=""
              class="input-group--focused"
              v-model="password"
            ></v-text-field>
          </v-flex>
          <v-flex xs12 sm6>
            <v-text-field
              :rules="[rules.required, rules.passwordMatch]"
              :type="'password'"
              name="input-10-2"
              label="Repeat Password"
              value=""
              class="input-group--focused"
            ></v-text-field>
          </v-flex>
          <v-btn color="primary" @click="e1 = 4">Continue</v-btn>
          <v-btn flat>Cancel</v-btn>
        </v-layout>
      </v-stepper-content>

      <v-stepper-content step="4">
        <v-alert :value="true" color="info" icon="info" outline>Please check if everything is correct.</v-alert>
        <v-layout column wrap>
          <h2>Name</h2>
          <p>{{name}}</p>

          <h2>Last Name</h2>
          <p>{{lastname}}</p>

          <h2>Username</h2>
          <p>{{username}}</p>

          <h2>E-Mail</h2>
          <p>{{email}}</p>

          <v-checkbox :label="checkbox1_text" v-model="checkbox1"></v-checkbox>
          <v-checkbox :rules="[rules.required]" :label="checkbox2_text" v-model="checkbox2"></v-checkbox>

          <v-btn color="primary" to="/">Finish & Go To Profile</v-btn>
        </v-layout>
      </v-stepper-content>
    </v-stepper-items>
  </v-stepper>
</template>

<script>
  export default {
    name: "SignUp",
    data() {
      return {
        e1: 0,
        show: false,
        name: '',
        lastname: '',
        username: 'tobeautogenerated',
        email: '',
        password: '',
        rules: {
          required: value => !!value || 'Required.',
          min: v => v.length >= 8 || 'Min 8 characters',
          emailValid: value => value.match('@') || 'E-Mail needs an @ in it',
          passwordMatch: value => value === this.password || 'Passwords don\'t match'
        },
        checkbox1: false,
        checkbox2: false,
        checkbox1_text: 'Allow Exmplox to send News Emails',
        checkbox2_text: 'Accept Terms and Conditions',
      }
    }
  }
</script>

<style scoped>

</style>
